In [1]:
import numpy as np
import pandas as pd

# Muestreo Polietápico

Si una vez seleccionada la muestra aleatoria de conglomerados, tomamos de alguna manera una muestra aleatoria de cada uno de ellos, estaremos realizando un **muestreo polietapico**.

## Ejemplo

Para realizar un muestreo polietapico usaremos el dataset de worldcup, podemos elegir una submuestra de 5 jugadores para cada uno de los 4 paises elegidos, obteniendo al final una muestra de tamaño 20 de todos los jugadores de la tabla de datos.

In [4]:
data = pd.read_csv('..\datasets\worldcup.csv', sep=',', index_col=0 )
data.sample(5)

               Team    Position  Time  Shots  Passes  Tackles  Saves
BoatengGh     Ghana  Midfielder   464     12     220       20      0
Melo         Brazil  Midfielder   291      2     249       12      0
Vorsah        Ghana    Defender   210      1      56        2      0
Vittek     Slovakia     Forward   353     10     118        0      0
Abidal       France    Defender   180      0      91        6      0

Paises Elegidos:

In [7]:
paises_elegidos = np.random.choice(data['Team'], 4, replace=False)
paises_elegidos

array(['Brazil', 'Slovenia', 'Italy', 'Argentina'], dtype=object)

Ahora elegimos a los 5 jugadores de cada pais:

In [8]:
mask = data['Team'].isin(paises_elegidos)
sample_data = data[mask].groupby('Team').apply(lambda s: s.sample(5))
sample_data

                            Team    Position  Time  Shots  Passes  Tackles  \
Team
Argentina Burdisso     Argentina    Defender   341      1     167        1
          Bolatti      Argentina  Midfielder    98      2      97        4
          Messi        Argentina     Forward   450     21     321       10
          Aguero       Argentina     Forward   106      2      57        2
          Gutierrez    Argentina  Midfielder   191      0      83       11
Brazil    Melo            Brazil  Midfielder   291      2     249       12
          Grafite         Brazil     Forward     5      0       4        0
          Fabiano         Brazil     Forward   418      9      89        4
          Elano           Brazil  Midfielder   140      5      57        6
          Josue           Brazil  Midfielder    46      0      54        1
Italy     Chiellini        Italy    Defender   270      2     155        7
          Di Natale        Italy     Forward   153      6      55        2
          De Rossi         Italy  Midfielder   270      3     204        9
          Marchisio        Italy  Midfielder   120      0      57        2
          Gilardino        Italy     Forward   117      1      32        0
Slovenia  Ljubijankic   Slovenia     Forward   173      2      36        2
          Novakovic     Slovenia     Forward   270      2      68        1
          Birsa         Slovenia  Midfielder   261      6      61        5
          Brecko        Slovenia    Defender   270      1      95        5
          Matavz        Slovenia     Forward    11      0       4        0

                       Saves
Team
Argentina Burdisso         0
          Bolatti          0
          Messi            0
          Aguero           0
          Gutierrez        0
Brazil    Melo             0
          Grafite          0
          Fabiano          0
          Elano            0
          Josue            0
Italy     Chiellini        0
          Di Natale        0
          De Rossi         0
          Marchisio        0
          Gilardino        0
Slovenia  Ljubijankic      0
          Novakovic        0
          Birsa            0
          Brecko           0
          Matavz           0